Repository tangle-network/blueprint, pull requests merged in 2025-05, with the labels that each got.

#940 chore: cargo update
  Cargo.lock
  examples/incredible-squaring/Cargo.lock
  workspace-hack/Cargo.toml
Labels: dependencies

#938 feat(manager)!: support verifying binaries with gh attestations
  Cargo.lock
  Cargo.toml
  cli/src/command/run/tangle.rs
  cli/src/main.rs
  cli/src/tests/tangle/run.rs
  crates/manager/Cargo.toml
  crates/manager/src/config.rs
  crates/manager/src/error.rs
  crates/manager/src/executor/event_handler.rs
  crates/manager/src/executor/mod.rs
  crates/manager/src/main.rs
  crates/manager/src/sdk/utils.rs
  crates/manager/src/sources/binary.rs
  crates/manager/src/sources/container.rs
  crates/manager/src/sources/github.rs
  crates/manager/src/sources/mod.rs
  crates/manager/src/sources/testing.rs
  examples/incredible-squaring/Cargo.lock
Labels: feature ➕, task ✔️

#984 feat: add support for request params
  cli/src/command/jobs/helpers.rs
  cli/src/command/service/request.rs
  cli/src/main.rs
  cli/src/tests/tangle/run.rs
  cli/src/tests/tangle/services.rs
Labels: needs review 👓, DO NOT MERGE
