Repository tangle-network/blueprint, pull requests merged in 2025-01, with the labels that each got.

#602 feat(blueprint-sdk): sdk error
  Cargo.lock
  crates/sdk/Cargo.toml
  crates/sdk/src/error.rs
  crates/sdk/src/lib.rs
Labels: feature ➕, p0 🔥

#604 feat(macros): use `sdk::Error` instead of `Box<dyn Error>`
  Cargo.lock
  crates/clients/eigenlayer/src/error.rs
  crates/config/src/lib.rs
  crates/config/src/protocol.rs
  crates/macros/blueprint-proc-macro/src/job/tangle.rs
  crates/sdk/Cargo.toml
  crates/sdk/src/error.rs
Labels: optimization ⚙️

#606 chore: cargo update
  Cargo.lock
Labels: dependencies

#620 chore(stores): remove `Default` bound on `LocalDatabase`
  crates/stores/local-database/src/lib.rs
Labels: optimization ⚙️

#621 feat(blueprint-metadata): nicer errors
  Cargo.lock
  crates/blueprint/metadata/Cargo.toml
  crates/blueprint/metadata/src/lib.rs
Labels: feature ➕
